name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe it below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem does this feature solve?
      placeholder: Currently, I can't... which makes it difficult to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: Add a command that allows users to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions have you thought about?
      placeholder: I considered using..., but it doesn't work because...
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Which Component?
      options:
        - VSCode Extension
        - MCP Backend
        - Both
        - Documentation
        - Other
    validations:
      required: true

  - type: checkboxes
    id: breaking
    attributes:
      label: Breaking Change
      description: Would this require breaking changes to existing functionality?
      options:
        - label: This is a breaking change (requires major version bump)
        - label: This is backward compatible

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Show how this feature would be used
      placeholder: |
        ```typescript
        // Example code or command usage
        ```
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Screenshots, mockups, related features, etc.
    validations:
      required: false
