/**
 * Markdown report generator for agent run logs and investigation docs.
 *
 * Two report types:
 * 1. Per-run report: `agents/<name>/runs/<timestamp>-run<NNNN>.md`
 *    - Full audit-trail style report of a single run
 * 2. Investigation doc: `docs/YYYY-MM-DD-HHmm-<agentName>.md`
 *    - One file per investigation run with LLM-written content
 *    - Each run creates a NEW file (not appended to a daily doc)
 */

import * as fs from 'fs';
import * as path from 'path';
import { AgentRunLog, AgentAction } from './types.js';

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Create a new investigation report file for this run.
 * Each run gets its own file with date+time in the filename for chronological ordering.
 * Returns the relative path from workspace root (e.g., `docs/2026-03-02-1430-error-monitor.md`).
 *
 * @param workspacePath     - Root workspace directory
 * @param agentName         - Agent name (used in filename)
 * @param runLog            - The completed run log
 * @param investigationReport - LLM-written markdown content for this run
 * @returns                 - Relative path to the investigation doc (from workspace root)
 */
export function createInvestigationReport(
    workspacePath: string,
    agentName: string,
    runLog: AgentRunLog,
    investigationReport: string
): string {
    const dateTimeStr = formatDateTimeForFilename(runLog.timestamp);
    const fileName = `${dateTimeStr}-${agentName}.md`;
    const docsDir = path.join(workspacePath, 'docs');
    const filePath = path.join(docsDir, fileName);
    const relativePath = `docs/${fileName}`;

    fs.mkdirSync(docsDir, { recursive: true });

    const header = buildInvestigationHeader(agentName, runLog.timestamp);
    fs.writeFileSync(filePath, header + investigationReport + '\n', 'utf-8');

    return relativePath;
}

/**
 * @deprecated Use createInvestigationReport instead. Kept for backward compatibility.
 * Creates a new investigation report file (no longer appends to a daily doc).
 */
export function appendToDailyReport(
    workspacePath: string,
    agentName: string,
    runLog: AgentRunLog,
    investigationReport: string
): string {
    return createInvestigationReport(workspacePath, agentName, runLog, investigationReport);
}

/**
 * Format a timestamp into a filename-safe date-time string: YYYY-MM-DD-HHmm
 */
function formatDateTimeForFilename(timestamp: string): string {
    const date = new Date(timestamp);
    const year = date.getUTCFullYear();
    const month = String(date.getUTCMonth() + 1).padStart(2, '0');
    const day = String(date.getUTCDate()).padStart(2, '0');
    const hours = String(date.getUTCHours()).padStart(2, '0');
    const minutes = String(date.getUTCMinutes()).padStart(2, '0');
    return `${year}-${month}-${day}-${hours}${minutes}`;
}

/**
 * Build the header for an investigation report file.
 */
function buildInvestigationHeader(
    agentName: string,
    timestamp: string
): string {
    const date = new Date(timestamp);
    const dateStr = timestamp.substring(0, 10);
    const timeStr = `${String(date.getUTCHours()).padStart(2, '0')}:${String(date.getUTCMinutes()).padStart(2, '0')} UTC`;

    const lines: string[] = [];
    lines.push(`# ${agentName} — Investigation Report — ${dateStr} ${timeStr}`);
    lines.push('');
    lines.push(`> Auto-generated by BC Telemetry Buddy agent runtime.`);
    lines.push('');
    lines.push('---');
    lines.push('');

    return lines.join('\n');
}

/**
 * Generate a Markdown string from a completed agent run log.
 *
 * @param runLog  - The run log produced by the runtime.
 * @returns       - Complete Markdown document as a string.
 */
export function generateRunReport(runLog: AgentRunLog): string {
    const lines: string[] = [];

    appendHeader(lines, runLog);
    appendSummaryTable(lines, runLog);
    appendInstruction(lines, runLog);
    appendStateAtStart(lines, runLog);
    appendToolCalls(lines, runLog);
    appendFindings(lines, runLog);
    appendAssessment(lines, runLog);
    appendActions(lines, runLog);
    appendStateChanges(lines, runLog);

    return lines.join('\n') + '\n';
}

// ─── Section Builders ─────────────────────────────────────────────────────────

function appendHeader(lines: string[], runLog: AgentRunLog): void {
    const runIdStr = String(runLog.runId).padStart(4, '0');
    const date = new Date(runLog.timestamp);
    const dateStr = date.toUTCString();

    lines.push(`# Agent Run Report: ${runLog.agentName} — Run #${runIdStr}`);
    lines.push('');
    lines.push(`> Generated: ${dateStr}`);
    lines.push('');
}

function appendSummaryTable(lines: string[], runLog: AgentRunLog): void {
    const durationSec = (runLog.durationMs / 1000).toFixed(1);

    lines.push('## Summary');
    lines.push('');
    lines.push('| Field | Value |');
    lines.push('|---|---|');
    lines.push(`| **Run ID** | ${runLog.runId} |`);
    lines.push(`| **Agent** | ${runLog.agentName} |`);
    lines.push(`| **Timestamp** | ${runLog.timestamp} |`);
    lines.push(`| **Duration** | ${durationSec}s |`);
    lines.push(`| **Model** | ${runLog.llm.model} |`);
    lines.push(`| **Total Tokens** | ${runLog.llm.totalTokens} (prompt: ${runLog.llm.promptTokens}, completion: ${runLog.llm.completionTokens}) |`);
    lines.push(`| **Tool Calls** | ${runLog.llm.toolCallCount} |`);
    lines.push('');
}

function appendInstruction(lines: string[], runLog: AgentRunLog): void {
    lines.push('## Instruction');
    lines.push('');
    lines.push('```');
    lines.push(runLog.instruction.trim());
    lines.push('```');
    lines.push('');
}

function appendStateAtStart(lines: string[], runLog: AgentRunLog): void {
    const s = runLog.stateAtStart;

    lines.push('## State at Start');
    lines.push('');
    lines.push('| Field | Value |');
    lines.push('|---|---|');
    lines.push(`| **Run Count** | ${s.runCount} |`);
    lines.push(`| **Active Issues** | ${s.activeIssueCount} |`);
    lines.push(`| **Prior Summary** | ${s.summary ? truncate(s.summary, 200) : '_none_'} |`);
    lines.push('');
}

function appendToolCalls(lines: string[], runLog: AgentRunLog): void {
    lines.push('## Tool Calls');
    lines.push('');

    if (runLog.toolCalls.length === 0) {
        lines.push('_No tool calls made._');
        lines.push('');
        return;
    }

    lines.push('| # | Tool | Duration | Result |');
    lines.push('|---|---|---|---|');

    for (const tc of runLog.toolCalls) {
        const durationMs = tc.durationMs < 1000
            ? `${tc.durationMs}ms`
            : `${(tc.durationMs / 1000).toFixed(1)}s`;
        const result = truncate(tc.resultSummary, 120).replace(/\|/g, '\\|').replace(/\n/g, ' ');
        lines.push(`| ${tc.sequence} | \`${tc.tool}\` | ${durationMs} | ${result} |`);
    }

    lines.push('');
}

function appendFindings(lines: string[], runLog: AgentRunLog): void {
    lines.push('## Findings');
    lines.push('');
    lines.push(runLog.findings || '_No findings recorded._');
    lines.push('');
}

function appendAssessment(lines: string[], runLog: AgentRunLog): void {
    lines.push('## Assessment');
    lines.push('');
    lines.push(runLog.assessment || '_No assessment recorded._');
    lines.push('');
}

function appendActions(lines: string[], runLog: AgentRunLog): void {
    lines.push('## Actions Taken');
    lines.push('');

    if (runLog.actions.length === 0) {
        lines.push('_No actions taken._');
        lines.push('');
        return;
    }

    for (const action of runLog.actions) {
        lines.push(`- **${action.type}** (${statusBadge(action)}) — ${formatActionDetails(action)}`);
    }

    lines.push('');
}

function appendStateChanges(lines: string[], runLog: AgentRunLog): void {
    const sc = runLog.stateChanges;
    const hasChanges =
        sc.issuesCreated.length > 0 ||
        sc.issuesUpdated.length > 0 ||
        sc.issuesResolved.length > 0 ||
        sc.summaryUpdated;

    lines.push('## State Changes');
    lines.push('');

    if (!hasChanges) {
        lines.push('_No state changes._');
        lines.push('');
        return;
    }

    if (sc.summaryUpdated) {
        lines.push('- Summary updated');
    }
    for (const id of sc.issuesCreated) {
        lines.push(`- Issue **created**: \`${id}\``);
    }
    for (const id of sc.issuesUpdated) {
        lines.push(`- Issue **updated**: \`${id}\``);
    }
    for (const id of sc.issuesResolved) {
        lines.push(`- Issue **resolved**: \`${id}\``);
    }

    lines.push('');
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function truncate(text: string, maxLen: number): string {
    if (text.length <= maxLen) return text;
    return text.slice(0, maxLen - 1) + '…';
}

function statusBadge(action: AgentAction): string {
    return action.status === 'sent' ? '✅ sent' : '❌ failed';
}

function formatActionDetails(action: AgentAction): string {
    if (!action.details) return action.type;
    const d = action.details;
    const parts: string[] = [];
    if (d['title']) parts.push(String(d['title']));
    if (d['channel']) parts.push(`channel: ${d['channel']}`);
    if (d['recipient']) parts.push(`to: ${d['recipient']}`);
    return parts.length > 0 ? parts.join(', ') : action.type;
}
